unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

Vagrant.configure("2") do |config|
	# Configure appGolang server
	config.vm.define "appGolang" do |appGolang|
		appGolang.vm.box = "ubuntu/bionic64"
		appGolang.vm.network "private_network", ip: "10.0.0.10"
		appGolang.vm.network "forwarded_port", guest: 8080, host: 8082
		appGolang.vm.provision "docker" do |dock|
			dock.build_image "/vagrant/", args: "-t golang:Final"
		end
		appGolang.vm.provision :shell do |shell|
			shell.inline = "docker run --publish 8080:8080 -t golang:Final &"
		end
	end
# Configure Jenkins server
	config.vm.define "appJenkins" do |appJenkins|
		appJenkins.vm.box = "ubuntu/bionic64"
		appJenkins.vm.network "private_network", ip: "10.0.0.11"
		appJenkins.vm.network "forwarded_port", guest: 8080, host: 8081
		appJenkins.vm.provision :docker
		appJenkins.vm.provision :docker_compose
		appJenkins.vm.provision :shell do |shell|
			shell.path = "docker_compose_up.sh"
		end
	end
end
