unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.network "forwarded_port", guest: 8080, host: 8080
	config.vm.provision :docker
	config.vm.provision :docker_compose
	config.vm.provision :shell do |shell|
		shell.path = "docker_compose_up.sh"
	end
end
